### ISSUE TITLE
Requirement, Design and Test specifications for data portal and REST api

### ISSUE THREAD

**Issue by sushma-ananda** [hubmapconsortium/hubmap-data-portal#104]
We presently do not have any requirements specifications, design specifications, test specs for actual data portal React app (non-prototype) or actual REST api (HCA-oriented). These documents ideally help us understand/bridge the gaps between team members and understand the feature implementations better. For example: when we say Login: what are features in dataportal and REST api we intend to implement. What is the usecase we want to have? is writing specification good or defining a usecase ? What do we intend to test in login /logout ? Do we really **NEED** to test redirect urls from test automation tool or manual test is sufficient ? Cypress recommends not to test redirect urls, so stubs are something we should heavily rely. Similarly, what are details of each feature/design/usecase we prefer to implement on dataportal. This appears to me is applicable to all features we intend to implement.

**Comment by mccalluc** [comment]
I absolutely agree that the lack of plans at this level is disconcerting. I think it's partly a result of the high-level organization of the project: The really abstract stuff that was being done earlier (personas, etc.) never got translated down to the level of what-goes-on-the-page, and I think we need to advocate for a single product owner for site design.

I'm not clear on what work is needed to close this issue. Perhaps talk post-standup?

**Comment by sushma-ananda** [comment]
comment by Chuck: I'll re-review this, unless I should wait? I think we should get better about testing... it wouldn't need to be this PR, and it doesn't need to be 100%, but should make a plan for it.

_Originally posted by @mccalluc in https://github.com/hubmapconsortium/hubmap-data-portal/pull/113#issuecomment-524851505_

@mccalluc Thanks for the suggestion on tests. Can you please share more details as in what test cases are you suggesting ?

**Comment by mccalluc** [comment]
Finer grained issues have been filed. Closing.
