### ISSUE TITLE
Scope of exhaustive tests for frontend browser using Cypress

### ISSUE THREAD

**Issue by sushma-ananda** [hubmapconsortium/hubmap-data-portal#106]
Consider an example: when we say front end testing in browser:
what do we want to test here - may be elements, react components, what is been conditionally loaded/visible/or not ? (example: login option appears when user logs in, logout option appears when user logs out and username disappears in frontend after logout). Do we want to test clicking/browser event options ? (example: mousemove and click material-ui menu options, but not click redirect urls (Http 303/304) etc). We might definitely should test this and not limit our testing to mere functonality, frontend testing includes testing options that load/change upon other actions (select/deselect a filter on search page, would impact results being displayed and adding filter tags ). Most of material-ui components are Hooks/HOCs so I guess, we should do tests when such frontend tests.

Given above:

1. We could have unit tests for testing specific implementation for each feature/enhancement.

1. We could have function tests/regression tests for develop branch, that are merged from feature branches to test every time a new merge happens.

1. We might as well want to test Production setting, after hosting for example on: https://data.dev.hubmapconsortium.org , so may be we can have production tests and from develop tests separately. Development tests are a green go-ahead for hosting in production but after hosting on production website, do we want to test hosted website for sanity, functionality tests ?

**Comment by mccalluc** [comment]
fresh start in flask-data-portal. Keeping it server-side for now. Closing.
