### ISSUE TITLE
Browse page for React

### ISSUE THREAD

**Issue by sushma-ananda** [hubmapconsortium/hubmap-data-portal#108]
Pull out the UI components from https://github.com/HumanCellAtlas/data-browser and build browse page as discussed in standup today.

**Comment by sushma-ananda** [comment]
HCA's databrowser uses angular & Typescript. However, porting to react appears to be not-agreed solution. Using this as baseline, create React components with similar search options displayed here. [W.I.P]

**Comment by ngehlenborg** [comment]
@sushma-ananda: it might be good to hold off a little bit on this. As far as I understand, we neither have the APIs to support the HCA UI nor talked about whether we actually want to use the same approach.

**Comment by sushma-ananda** [comment]
@ngehlenborg Please accept my sincere apologies that this came across as not discussed. 
Sure, I will be glad to pause working on this, given today's discussion about graphics designer. I would like to share a background to creating this issue :
>  Actually, this came up during one of virtual stand ups earlier this week since I wanted to check if a browse page was something that collides with anyone else's work/suggestions, since that was something I have been working on. I **attempted** to actually take a look at HCA's data browser after yesterday's call - to understand the dependencies/cohesion to other HCA modules. More specifically, since Prof. Ziv suggested to refer HCA [Explore](https://data.humancellatlas.org/explore/projects) page - perhaps the search options on the page, until we have a wireframe. It turned out HCA's data browser - is not portable to react and appears to have high cohesion (functional dependency on other HCA modules). So I just ended up updating a very generic summary of it in this issue, awaiting tomorrow's call- thinking, that it was probably more relevant to share details of my findings and discuss further about alternatives, tomorrow.

**Comment by ngehlenborg** [comment]
Thanks for the clarification.

**Comment by mccalluc** [comment]
[Issues for mocking up browse pages in flask-data-portal](https://github.com/hubmapconsortium/flask-data-portal/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+mockup+list). Closing.
