### ISSUE TITLE
SASS vs. SCSS vs. LESS?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-data-portal#109]
Any of these would make our stylesheets easier to manage.

- LESS: CSS superset
- SASS: Yaml-influenced syntax 
- SCSS: SASS internals, but expressed as a CSS superset

Which should we use? I would prefer to use a CSS-superset, and my sense is that SCSS is more active, and projects (for example, bootstrap) have transitioned from LESS to SASS/SCSS. Other thoughts?

**Comment by ngehlenborg** [comment]
I recommend SASS/SCSS. Seems to be the move common choice today.

**Comment by mruffalo** [comment]
Sounds good to me. I agree about using a CSS superset, so SASS/SCSS it is. I'll resurrect and merge Chuck's PR.
