### ISSUE TITLE
update all elements to include data-* tags

### ISSUE THREAD

**Issue by sushma-ananda** [hubmapconsortium/hubmap-data-portal#111]
Again, writing tests that depend on element IDs and DOM structure is deprecated: https://docs.cypress.io/guides/references/best-practices.html#Selecting-Elements ... though I think for us going all the way to `cy-data` is too probably far: Makes the tests less readable, for a small decrease in fragility. Our site is small enough that if the wording did change, that would be worth changing the test, I think.

_Originally posted by @mccalluc in https://github.com/hubmapconsortium/hubmap-data-portal/pull/103_

**Comment by mccalluc** [comment]
Note that my comment is that this would be overkill for us: Matching on strings is sufficiently robust, and much easier to read and write. I would like to close this. cc @mruffalo
