### ISSUE TITLE
Mimic HCA browse page via React/etc. components

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/hubmap-data-portal#123]
Example: https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22%3A%22organ%22%2C%22terms%22%3A%5B%22blood%22%5D%7D%5D

For now, we can hardcode the facets (Donor, Tissue Type, Specimen) and filter criteria (Donor -> Genus Species, Organism Age, etc.) in the backend.

**Comment by mccalluc** [comment]
Issues to mockup list UI are filed with [flask-data-portal](https://github.com/hubmapconsortium/flask-data-portal/issues?utf8=%E2%9C%93&q=is%3Aissue+mockup+list). Closing.
