### ISSUE TITLE
Import more than two levels of metadata from HCA spreadsheets

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/hubmap-data-portal#125]
Currently, we are only importing `donor_organism` and `specimen_from_organism` fields. Extract as much as we can from the HCA metadata, to build as full a provenance graph as possible.

**Comment by mccalluc** [comment]
Ingest API development is happening in https://github.com/hubmapconsortium/ingest-ui, and I've filed [an issue](https://github.com/hubmapconsortium/ingest-ui/issues/19) for supporting HCA ingest there.
