### ISSUE TITLE
Make HCA metadata import idempotent

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/hubmap-data-portal#127]
Currently, running the same import multiple times will fail due to duplicate IDs in the MongoDB database. Improve the metadata import so that the same spreadsheet can be "imported" multiple times, with successive runs being no-ops.

**Comment by mccalluc** [comment]
API development is underway in https://github.com/hubmapconsortium/entity-api. This repo does not need to worry about importing HCA metadata.
