### ISSUE TITLE
list all entities for a given type on a page

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/hubmap-data-portal#131]
For each entity in the data model we need to provide a view to list these entities. The view should provide a title or name for the entity and metadata (creation date, UUID, HUBMAP accession number, if available) about the entity. The list is sorted in reverse chronological order based on creation date. From that list, the user should be able to navigate to a detail view for an individual entity. 

Note that for the core entities, this view will ultimately be replaced with a full faceted browsing interface.

Minimum acceptance criteria: list all entity UUIDs unsorted and provide a link to the detail view.

Related to #20.

**Comment by sushmaanandakoju** [comment]
@ngehlenborg so at the moment, this is not yet implemented. As per my understanding, I see that there are two options user can view: 1) The table/entities lists on mock browse page has to provide : sort, filter and click options. So when user clicks on individual entity from entities list, user navigates to entity detail page: where user can further see a list of filtered entities that are of same type as displayed on entity detail page.  2) Upon clicking on an individual entity: besides displaying entity details, we also display all entities of the same type. These listed entities on entity detail page can do same as in point 1) above. This means: user can navigate to any individual entity and have the individual entity also display all entities of same type, that can further be sorted, filtered and clicked. Can you please let me know your thoughts on this and if I understand this correctly ?

**Comment by mccalluc** [comment]
@sushma-ananda : I think your work for #153 may cover this. Please make a PR for that so your code can be reviewed. (Normally, we would make mock-ups and try to get some feedback from users before going straight to coding, but it didn't work that way this time.)

**Comment by sushmaanandakoju** [comment]
I would wait until Nils has assigned any further task. @ngehlenborg @mruffalo as per Chuck's text above: the process seems like this: _Normally, we would make mock-ups and try to get some feedback from users before going straight to coding, but it didn't work that way this time_ , can you please help let me know is this the agreed process ? 

@mccalluc #153 is not done. ofcourse, a PR will be created for review, as always, when completed.

**Comment by mccalluc** [comment]
Covered by [#11](https://github.com/hubmapconsortium/flask-data-portal/issues/11) [#12](https://github.com/hubmapconsortium/flask-data-portal/issues/12) [#13](https://github.com/hubmapconsortium/flask-data-portal/issues/13) in flask-data-portal.
