### ISSUE TITLE
list all entity types on a page

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/hubmap-data-portal#133]
Provide a list of all available entity types in the data portal sorted by name of the entity. The list should also show the total number of entities of each type that are currently in the portal. Clicking on the name of an entity navigates to a list of entities of the given type, as described in #131.

Minimum acceptance criteria: list all entity types and provide a link to the entity list page.

**Comment by sushmaanandakoju** [comment]
@ngehlenborg does listing all entity types is going to be on separate page like have a menu option on header: browse entity types ? something like we can provide an option to just view all entity types and user can click on an entity to further list all entities of same type ?

**Comment by mccalluc** [comment]
Stated another way: There is currently a pulldown in the header which looks like this:
<img width="192" alt="Screen Shot 2019-09-20 at 4 48 55 PM" src="https://user-images.githubusercontent.com/730388/65358070-a92fcb00-dbc6-11e9-9eb0-339a8d82c7aa.png">

I believe your acceptance criteria are satisfied: Close, or clarify the work that should be done? (Assigning to Nils to make clear whose court the ball is in: Reassign with clarification, or we can find a different work flow.)

**Comment by ngehlenborg** [comment]
For the first sprint we will be using the following entity types as per @shirey in https://github.com/hubmapconsortium/hubmap-data-portal/issues/138#issuecomment-537116792: Donor, Sample, DataSet

**Comment by mccalluc** [comment]
This is covered by the homepage work in flask-data-portal: https://github.com/hubmapconsortium/flask-data-portal/issues/18. Closing.
