### ISSUE TITLE
show details for a given entity on a page

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/hubmap-data-portal#134]
For a given entity, provide a "detail view" that shows all metadata available for the entity as a tabular view of key-value pairs sorted by key. Nested information should be expandable. Cross-references to other entities should be accessible via a link to the corresponding detail page for that entity. This view should be generic and work for any entity type. The detail view for a given entity will be accessible via the entity list described in #131.

Note that for core entities, this view will ultimately be superseded by custom views. For the first iteration, provenance information does not need to be displayed, but future iterations will need to provide a generic provenance view as well (related to #7). Also, the detail view should be a component that can be embedded in different parts of the portal but for the first iteration, it will be on a separate page.

Minimum acceptance criteria: as above.

Related to #16, #11, #66.

**Comment by sushmaanandakoju** [comment]
@ngehlenborg currently, I have not yet started working on this. Given that, I have started with #153 , I was thinking this is the next natural step: now that list of entities are displayed (mocked), can have a) click on an entity and navigates to entity detail page. I am thinking on starting on this one. However, we do not have elastic search/ne4j api/provenance api for now. So I am going to mock this entity detail page by considering past discussions about [4dn fourfront entity detail page](https://data.4dnucleome.org/experiment-set-replicates/4DNES6IJ8J3X/) as well as [HCA entity detail page](https://data.humancellatlas.org/explore/projects/74b6d569-3b11-42ef-b6b1-a0454522b4a0). I believe that generic entity detail page is assumed to display entity details that which we want to display without having to login/authenticate. Can you please let me know, like if this is fine to ahead with ?

**Comment by mccalluc** [comment]
Waiting for feedback on #154 before continuing.

**Comment by mccalluc** [comment]
The plan approved in #154 has been implemented in flask-data-portal... with the exception of links between entities. Filed https://github.com/hubmapconsortium/flask-data-portal/issues/19. Closing.
