### ISSUE TITLE
agree on an initial sitemap for the data portal

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/hubmap-data-portal#135]
Propose a site structure for key components of the portal (browse, help, about, search, etc.) and collect one round of feedback from portal team.

Minimum acceptance criteria: as above.

**Comment by mccalluc** [comment]
Initial minimal sitemap proposed at https://docs.google.com/document/d/1oLyozEaQyBkTs6ezXQBCXEbNyGm7Xxw1H1xjOf9pQAA/edit?usp=sharing -- will drop link in Slack.

**Comment by ngehlenborg** [comment]
The revised proposal is looking fine, closing this issue and moving on to #136.
