### ISSUE TITLE
Create mockup for generic entity browse page

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/hubmap-data-portal#153]
Create a UI mockup for the generic entity list view as described in #131. Collect and incorporate one round of feedback from data portal team.

Minimum acceptance criteria: as above.

Related to #108, #123.

**Comment by sushmaanandakoju** [comment]
@ngehlenborg I have been working on mocking browse page similar to HCA, for now. The idea is to have browse page as simple and as generic as possible so we can build from there a UI design of look-and-feel as we discuss/receive feedback or UI design template, I believe. This branch has mock data browse page that uses search facets and experiments details populated from mock json. https://github.com/hubmapconsortium/hubmap-data-portal/tree/mock-data-browse and attached image is quick glimpse of same . This was the one I was hoping to demo in today's meeting and discuss. Can you please let me know your thoughts on this ?
![Browse-page-mockup](https://user-images.githubusercontent.com/8979477/65338807-f7c67080-db98-11e9-91cd-fcc22a2c0882.png)

**Comment by sushmaanandakoju** [comment]
I have created a document to summarize Browse page today, as per process recommended by Chuck : https://docs.google.com/document/d/1rWJMt5Wx617OZ-U6HZf2JTBQwc1XuiZ43NZ9H28Zu_Q/edit?usp=sharing for further inputs/comments

**Comment by mccalluc** [comment]
We know nothing about what fields will be available from the API, so for now just going to make a table of links. Closing.
