### ISSUE TITLE
Create mockup for generic entity detail page

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/hubmap-data-portal#154]
Create a UI mockup for the generic entity detail view as described in #134. Collect and incorporate one round of feedback from data portal team.

Minimum acceptance criteria: as above.

**Comment by sushmaanandakoju** [comment]
@ngehlenborg currently, I have not yet started working on this. Given that, I have started with #153 , I was thinking this is the next natural step: now that list of entities are displayed (mocked), can have a) click on an entity and navigates to entity detail page. I am thinking on starting on this one. However, we do not have elastic search/ne4j api/provenance api for now. So I am going to mock this entity detail page by considering past discussions about 4dn fourfront entity detail page as well as HCA entity detail page. I believe that generic entity detail page is assumed to display entity details that which we want to display without having to login/authenticate. Can you please let me know, like if this is fine to go ahead with ?

**Comment by mccalluc** [comment]
Yep: please take this on if it interests you! I'd suggest making the mockup either as a google doc drawing, or with figma, so that with the feedback you'll get it'll be easy to adjust position and size of components.

**Comment by sushma-ananda** [comment]
ofcourse, sure, glad to work on a mockup and share for everyone's feedback.

**Comment by mccalluc** [comment]
Sorry: Change of course: Focus on the browse page, and I'll do the details page.

**Comment by mccalluc** [comment]
[Proposal ready for comments](https://docs.google.com/document/d/106GoZZe88l--ljloem3PoWo8t-2K_-e8FIj-mikUmfc/edit?usp=sharing) -- Will post in slack.

**Comment by ngehlenborg** [comment]
@mccalluc: The proposal as of 9/30/19 is looking good and I suggest that we move ahead with this.
