### ISSUE TITLE
Server-side rendering? Back to plain Django?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-data-portal#162]
We have two serious, related, problems:
- Book-marked links do not work: If I navigate to experiments, and then reload [`/experiments`](https://data.dev.hubmapconsortium.org/experiments) I get a 404 from Django.
- If a bot tries to spider our site, it will fail, because all the content is being done on the client-side.

The "F" in "FAIR" is *findable*, and if we're not getting indexed by search engines, we're not findable.

Options:
- Add a simple fallback to `urls.py`: Links can be book marked, but search engines will still not see our content. (This feels like a particularly bad choice for a data repository.)
- [Server side rendering](https://css-tricks.com/server-side-react-rendering/)
- Go back to plain django, only using React for on-page components.

I myself have never done React server-side rendering: It's not an exotic technology at this point, but with resources we have, it may be safer to stay with Django for the UI.

(Prompted by Matt's note in #160.)

**Comment by ngehlenborg** [comment]
Can you clarify what you mean by „bookmarked“ link?

**Comment by mccalluc** [comment]
> Can you clarify what you mean by „bookmarked“ link?

When you navigate the site it is only updating the HTML5 History -- The URLs you see will not work if you try to reload them. For example:
- Begin at [https://data.dev.hubmapconsortium.org/](https://data.dev.hubmapconsortium.org/) (Ignore the errors on this page: Not relevant.)
- In the header, click on "Browse" > "Data Analysis": The URL is now [https://data.dev.hubmapconsortium.org/dataanalysis](https://data.dev.hubmapconsortium.org/dataanalysis). (Ignore the errors on this page, too.)
- Reload that page: You just get a 404 from Django: "Not Found: The requested resource was not found on this server."

**Comment by sushmaanandakoju** [comment]
I and Matt had a discussion about client side rendering (CSR) vs Server Side Rendering (SSR), but it was for prototype. Create-react-app is client-side rendering but we are serving static pages from Django, per this issue summary. 

We do know NCI GDC, HCA portals do use server-side rendering, all using different SSR approaches, I think.

For a release version, SSR with Search-engine-optimization for react will be required I think. We can : 

1. use next.js or gatsby [comparison of the gatsby and next.js] (https://www.gatsbyjs.org/features/jamstack/gatsby-vs-nextjs/) or any tools for SSR. 

1. we might want to have SEO in django besides express + react-transmit as quoted in the issue.

One question: _**do we know if NIH web projects should follow any specific guidelines for web portal development? so we can consider such policies/guidelines also besides server-side rendering.**_

**Comment by ngehlenborg** [comment]
@sushma-ananda: "Create-react-app is client-side rendering but we are serving static pages from Django, per this issue summary." What are you referring to by "per this issue summary"?

**Comment by sushmaanandakoju** [comment]
@ngehlenborg by "per this issue summary" I meant as per the summary provided by Chuck [162](https://github.com/hubmapconsortium/hubmap-data-portal/issues/162#issue-497701649). I have a question: are there any guidelines/recommendations for NIH projects for web UI templates, implementation, web hosting ??

**Comment by mccalluc** [comment]
@sushma-ananda : No, the NIH is not going to dictate any of those details. There are rules that matter (HIPAA, ADA) but NIH is not concerned about implementation.

**Comment by sushma-ananda** [comment]
@mccalluc, thanks for letting me know, glad to know that there aren't any NIH recommendations.

**Comment by sushmaanandakoju** [comment]
@mccalluc thank you, good to know that there aren't any such recommendations.

**Comment by mccalluc** [comment]
Making a fresh start in flask-data-portal, and not carrying over any of the React code for now. Closing.
