### ISSUE TITLE
allow react/prop-types and any other eslint rules/exceptions. 

### ISSUE THREAD

**Issue by sushmaanandakoju** [hubmapconsortium/hubmap-data-portal#168]
If you don't believe we should follow this guideline, please make a separate PR for that.

_Originally posted by @mccalluc in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3Mjk0NDA2MzMz/pull_request_reviews/more_threads_

**Comment by mccalluc** [comment]
Making a fresh start in flask-data-portal, and not carrying over any of the React code for now. Closing.
