### ISSUE TITLE
Credentials checked in in App.js? Compromised?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-data-portal#170]
These lines were checked in to App.js: What were they for? Has any service been compromised by having this information checked in?
```
// import '@google/model-viewer' ;
// npm run setup -- --spaceId eo4e2dc0pbyt --deliveryToken H3bSZhVoA8_0_hjDzD6yGsq1jHCdBgxop3iJ9EM54B8 --managementToken CFPAT-nXzmTIQFv4Om1KFSnqn0fS3X7_3YLXDacst4IC52_1M
/* TODO: add chart
*   DONE: Add api get results fron django to populate results for each tissue
*      DONE: Added organs prototype + clickable+rest api!! phew!! */
```

**Comment by sushmaanandakoju** [comment]
Thanks for pointing this out. Apologize for the credentials of third party api from June, 2019. will update shortly.

**Comment by mccalluc** [comment]
Making a fresh start with flask-data-portal, and not using this API. (I would encourage you to delete/refresh your keys with that service, but that's in your court.)
