### ISSUE TITLE
set up persistent routes in Django

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/hubmap-data-portal#173]
As discussed in #162, there is currently no support for persistent routes. We need to set this up as quickly as possible in order to move forward with the implementation of #131, #133, #134, and #136. 

@mccalluc and I discussed the pros and cons of doing this with (1) server-side rendering for a single React app versus (2) routing in Django with React components embedded in Django templates and decided to move forward with (2) in the interest of time. We will revisit this in the future when clearer use cases emerge.

Minimum acceptance criteria: routing set up in Django and ready to be extended as required by #131, #133, #134, and #136.

**Comment by mccalluc** [comment]
@sushma-ananda : desired pages were decided in #135.

**Comment by sushma-ananda** [comment]
@mccalluc As per our discussion, summary is as follows for first PR for this issue :
1) Please just echo the entity-type and id in the URL: Hitting the API is separate.
2) Please just something like <html><body>This is the Organ browse page</body></html>: I just need to see that the routing works, nothing more.
3) Group all entities (all types ) into single page. 
4) Have individual entity-list page (show lists by entity types). 
5) Have individual browse entity detail page (broadly 3 pages each for each of entity types). 
6) And test the routing. One or the other, or both, of cypress testing and django unit testing.

Once all 1 through 6 are completed, will go ahead and create the PR, as we discussed.
Please let me know if I missed anything/this needs to be updated. Thanks!

**Comment by sushmaanandakoju** [comment]
@mccalluc As per our discussion, summary is as follows for first PR for this issue :
1) echo the entity-type and id in the URL: Hitting the API is separate.
2) add as suggested by Chuck. quote Chuck's message: "<html><body>This is the Organ browse page</body></html>: I just need to see that the routing works, nothing more."
3) Group all entities (all types ) into single page. 
4) Have individual entity-list page (show lists by entity types). 
5) Have individual browse entity detail page (broadly 3 pages each for each of entity types). 
6) And tests for the routing. One or the other, or both, of cypress testing and django unit testing.
7) There will be no models: Data will be pulled from the API, which is not under Django’s ORM.**

Once all 1 through 6 are completed, will go ahead and create the PR, as we discussed.
Please let me know if I missed anything/this needs to be updated. Thanks!

**Comment by mccalluc** [comment]
Please do this in a new, empty django app so that this can be distinguished from from all the old cruft that needs to be removed.

**Comment by sushma-ananda** [comment]
That is helpful, thanks for heads up.

**Comment by mccalluc** [comment]
Starting with clean slate in flask-data-portal; Routes have been implemented there.
