### ISSUE TITLE
Create json schema for provenance

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/hubmap-data-portal#183]

**Comment by mccalluc** [comment]
@mruffalo had done some work earlier re-using the component from 4DN: I suggest defining a schema based on what that component already expects, though it's possible that was too focused on the UI aspects.

**Comment by mccalluc** [comment]
Close in favor of https://github.com/hubmapconsortium/entity-api/issues/1. (I've also linked to the 4DN work there.)
