### ISSUE TITLE
Fresh start: React dev server --> Django dev server

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-data-portal#187]
Not confident that this is correct, but I think we do not need the React dev server: Instead we want to run Django in development mode. (Filling #188 to get webpack hot-reloading working.)

**Comment by mruffalo** [comment]
The development Docker config already runs Django in development mode to provide the API for the React app, so none of that needs to change. The `index.html` template served from the `frontend app` currently just says "look at the React frontend instead", so that would need to change.

**Comment by mccalluc** [comment]
Starting with clean slate in flask-data-portal. Closing.
