### ISSUE TITLE
Integrate data model from 4DN

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/hubmap-data-portal#19]
Many of the data schema definitions from https://github.com/4dn-dcic/fourfront/tree/master/src/encoded/schemas should be directly usable in the HuBMAP data portal. Use as much of this as possible, with appropriate backend storage. Ensure that we have IEC support for this, in terms of the provenance graph database they're working on

**Comment by mruffalo** [comment]
Something to identify right away: how much of Django's ORM can we use? How much of the [SnoVault](https://github.com/4dn-dcic/snovault} project will we need to use/adapt?

**Comment by mccalluc** [comment]
The project has moved in a different direction, for better or worse. Closing.
