### ISSUE TITLE
Add list views for all appropriate data types

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/hubmap-data-portal#20]
The full data model for the data portal will contain many different types: experiments, labs, awards/grants, publications, data types, processing pipelines, raw data files, pipeline runs (raw data as input, processed data as output).

Identify which data types we should allow implementing lists of all such objects. E.g., would a user be interested in listing all workflows which we're using?

**Comment by mccalluc** [comment]
The basic list of top-level types is defined in https://github.com/hubmapconsortium/hubmap-data-portal/issues/138#issuecomment-537116792: 
> Donor, Sample, Dataset

I've filled issues to create mockups. (Ask for implementation issues to be filed when mockups are done.)

- Mockup: Dataset list UI: #196 
- Mockup: Sample list UI: #195 
- Mockup: Donor list UI: #194
