### ISSUE TITLE
Specify and implement minimal API whereby Airflow signals ingest UI that an ingest request has succeeded or been rejected

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/hubmap-data-portal#206]

**Comment by frdougal** [comment]
Hi @jswelling , here is my proposal for the API.  

Endpoint PUT: /datasets/<identifier>/workflow_process.  

The PUT will send a JSON object like: 
{
  "dataset_status": "[QA|REJECTED]",
  "message": "<an output message from the Airflow API containing any errors",
  "ariflow_id": "<ideally this should be a single identifier resolving to the workflow run against identifier in endpoint URL.>",
  "timestamp": "<a timestamp when the workflow was completed (or last updated)>",
  "airflow_server_url": "<the url of the Airflow server>"
}
