### ISSUE TITLE
Basic multi-"page" functionality

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/hubmap-data-portal#21]
Despite being a single "page" from the perspective of the web server, the data portal will need to have multiple distinct "pages":
- Front page (already partially implemented)
- More detailed list of experiments/data
- Detail view for one experiment
- List(?) of pipelines
- Login page
- ... and probably many more

Implement multi-"page" functionality in some appropriate way. A good step 1 would probably be implementing a login page -- this will ensure that the core functionality of "replace content between the header and footer" works.

**Comment by mccalluc** [comment]
Closing.
