### ISSUE TITLE
Why is ipython in requirements.txt?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-data-portal#23]
A common convention is to have a separate requirements-dev.txt for development dependencies, and that might be a better place for this.

**Comment by mruffalo** [comment]
I was using an interactive Python shell quite a bit while troubleshooting some fixtures (related to #17), and I realize how much I take IPython for granted. It definitely isn't required for the production application container, and I'm still tweaking some of the development container configuration, so I'll be happy to move it to a new `requirements-dev.txt` to be installed in the development container.
