### ISSUE TITLE
Integrate Globus SSO

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/hubmap-data-portal#3]
Users should be able to authenticate through Globus. This will be used for both authentication and authorization to download sensitive data.

**Comment by mruffalo** [comment]
Good progress with Globus login and making parts of the API require authentication/authorization. Next steps:

1. Integrate with the React app: have the "login" link point to `/login/globus`
1. When a user is logged in, show some user data in the React app, like name and email for now. The most important part of this is demonstrating *some* communication between the React app and the DRF authorization framework. Details about what to show (username, etc.) aren't quite as important
1. When a user is logged in, provide a functional "logout" link.

**Comment by sushma-ananda** [comment]
HI @mruffalo , thanks for detailed steps and helping with globus configurations. As per React app side:
1) We do have /login/globus urls but it seems, the urls are not relative in development configurations. But given that, atm, the globus auth login/logout urls are external urls to React app.
Likewise, in Django app as well, we redirect to react app's external url in settings. This holds true for development.
2) User's logged in status with user's first_name/email are retrieved by setting cookies and are displayed on react app.
3) There is a logout option in logged in menu once user successfully logins. 

Assumption: The relative urls already exist in production and would work. So the master branch needs to be updated with relative urls when merging globus-auth to master and testing the same after hosting to production. 
There is a mock globus authentication implemented at [globus-auth](https://github.com/hubmapconsortium/hubmap-data-portal/tree/globus-auth) branch, do you think we can configure the relative urls or any other alternative to use relative urls in docker dev configurations ?
