### ISSUE TITLE
Do we care about the order of python imports?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/hubmap-data-portal#60]
If we don't, no action required.
If we do, [isort](https://pypi.org/project/isort/) can sort imports, or just warn about imports out of order.

**Comment by mruffalo** [comment]
I definitely care about this; I always group by [standard library, third-party, project internal], and sort alphabetically inside each group.

Thanks very much for the suggestion of `isort`; I'm preparing a PR that sorts all imports and adds import order checking to the `flake8` run in Travis.

**Comment by mruffalo** [comment]
Addressed in #61.
