### ISSUE TITLE
Add API and pages for listing patients/donors

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/hubmap-data-portal#66]
As per our recent data portal discussions, we're going to push a "fundamental" data type through the entire data portal architecture, from ingestion to data persistence to API access to display in the web interface.

Start this in the API and web interface by adding API endpoints for listing patients/donors and for showing all detailed information about a patient/donor.

**Comment by mccalluc** [comment]
API development and front-end development have been moved to separate repos.
